import { BaseGearAffix } from "./types";

export const BOW_TOWER_SEQUENCE_AFFIXES = [
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "+200% Precise Projectiles Aura effect\n-30% additional Precise Projectiles Sealed Mana Compensation",
    valueRanges: [],
    rawAffix:
      "`+200`% Precise Projectiles Aura effect<> `-30`% additional Precise Projectiles Sealed Mana Compensation",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "+30% additional Deterioration Damage\n10% chance to inflict 2additional stack(s) of Deterioration",
    valueRanges: [],
    rawAffix:
      "`+30`% additional Deterioration Damage<> `10`% chance to inflict `2`additional stack(s) of Deterioration",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "+50% Elemental Damage for the gear\n-25% gear Physical Damage",
    valueRanges: [],
    rawAffix:
      "`+50`% Elemental Damage for the gear<> `-25`% gear Physical Damage",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "+80% gear Physical Damage\n-20% Attack Critical Strike Rating for this gear",
    valueRanges: [],
    rawAffix:
      "`+80`% gear Physical Damage<> `-20`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "Adds 1- 7Lightning Damage to Attacks per 10Dexterity",
    valueRanges: [],
    rawAffix: "Adds `1`- `7`Lightning Damage to Attacks per `10`Dexterity",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "Adds 3- 5Fire Damage to Attacks per 10Strength",
    valueRanges: [],
    rawAffix: "Adds `3`- `5`Fire Damage to Attacks per `10`Strength",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "Attack Horizontal Projectiles will return after reaching their max range and will hit enemies on their path again\n-30% additional Projectile Damage",
    valueRanges: [],
    rawAffix:
      "Attack Horizontal Projectiles will return after reaching their max range and will hit enemies on their path again<> `-30`% additional Projectile Damage",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "Enemies have a 30% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to 25% of their Max Life to enemies within a 5m radius",
    valueRanges: [],
    rawAffix:
      "Enemies have a `30`% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to `25`% of their Max Life to enemies within a `5`m radius",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "Main Skill is supported by Lv. 25Multiple Projectiles\n+25% additional Projectile Damage",
    valueRanges: [],
    rawAffix:
      "Main Skill is supported by Lv. `25`Multiple Projectiles<> `+25`% additional Projectile Damage",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+12% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "`+12`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+16% all stats",
    valueRanges: [],
    rawAffix: "`+16`% all stats",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+16% additional damage for Weapons",
    valueRanges: [],
    rawAffix: "`+16`% additional damage for Weapons",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+16% Cold Penetration",
    valueRanges: [],
    rawAffix: "`+16`% Cold Penetration",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+16% Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "`+16`% Erosion Resistance Penetration",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+16% Fire Penetration",
    valueRanges: [],
    rawAffix: "`+16`% Fire Penetration",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+16% Lightning Penetration",
    valueRanges: [],
    rawAffix: "`+16`% Lightning Penetration",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+20% additional damage on Critical Strike",
    valueRanges: [],
    rawAffix: "`+20`% additional damage on Critical Strike",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+20% Attack Critical Strike Rating for this gear",
    valueRanges: [],
    rawAffix: "`+20`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentTypeKey: "bow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+8% gear Attack Speed",
    valueRanges: [],
    rawAffix: "`+8`% gear Attack Speed",
  },
] as const satisfies readonly BaseGearAffix[];

export type BowTowerSequenceAffix = (typeof BOW_TOWER_SEQUENCE_AFFIXES)[number];
