import { BaseGearAffix } from "./types";

export const CROSSBOW_BASE_AFFIX_AFFIXES = [
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Lucky Critical Strike\n{0}% Critical Strike Rating",
    valueRanges: [
      {
        min: -40,
        max: -50,
      },
    ],
    rawAffix: "Lucky Critical Strike<> `(-40--50)`% Critical Strike Rating",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Agility Blessing Stacks +2",
    valueRanges: [],
    rawAffix: "Max Agility Blessing Stacks `+2`",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Focus Blessing Stacks +2",
    valueRanges: [],
    rawAffix: "Max Focus Blessing Stacks `+2`",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Tenacity Blessing Stacks +2",
    valueRanges: [],
    rawAffix: "Max Tenacity Blessing Stacks `+2`",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: "+{0}% Armor DMG Mitigation Penetration",
    valueRanges: [
      {
        min: 10,
        max: 14,
      },
    ],
    rawAffix: "`+(10-14)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: "+{0}% Elemental and Erosion Resistance Penetration",
    valueRanges: [
      {
        min: 12,
        max: 16,
      },
    ],
    rawAffix: "`+(12-16)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: "+{0}% gear Physical Damage",
    valueRanges: [
      {
        min: 48,
        max: 64,
      },
    ],
    rawAffix: "`+(48-64)`% gear Physical Damage",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: "+2Horizontal Projectile Penetration(s)",
    valueRanges: [],
    rawAffix: "`+2`Horizontal Projectile Penetration(s)",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: "Adds {0}- {1}Physical Damage to the gear",
    valueRanges: [
      {
        min: 64,
        max: 68,
      },
      {
        min: 80,
        max: 84,
      },
    ],
    rawAffix: "Adds `(64-68)`- `(80-84)`Physical Damage to the gear",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: "Projectile Quantity +2",
    valueRanges: [],
    rawAffix: "Projectile Quantity `+2`",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "+{0}% Attack Speed",
    valueRanges: [
      {
        min: 12,
        max: 16,
      },
    ],
    rawAffix: "`+(12-16)`% Attack Speed",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "+{0}% Elemental Damage",
    valueRanges: [
      {
        min: 40,
        max: 48,
      },
    ],
    rawAffix: "`+(40-48)`% Elemental Damage",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "+{0}% Erosion Damage",
    valueRanges: [
      {
        min: 40,
        max: 48,
      },
    ],
    rawAffix: "`+(40-48)`% Erosion Damage",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "+{0}% Physical Damage",
    valueRanges: [
      {
        min: 40,
        max: 48,
      },
    ],
    rawAffix: "`+(40-48)`% Physical Damage",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "+{0}% Ranged Damage",
    valueRanges: [
      {
        min: 40,
        max: 48,
      },
    ],
    rawAffix: "`+(40-48)`% Ranged Damage",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds {0}- {1}Lightning Damage to Attacks",
    valueRanges: [
      {
        min: 1,
        max: 3,
      },
      {
        min: 60,
        max: 65,
      },
    ],
    rawAffix: "Adds `(1-3)`- `(60-65)`Lightning Damage to Attacks",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds {0}- {1}Cold Damage to Attacks",
    valueRanges: [
      {
        min: 24,
        max: 29,
      },
      {
        min: 34,
        max: 39,
      },
    ],
    rawAffix: "Adds `(24-29)`- `(34-39)`Cold Damage to Attacks",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds {0}- {1}Fire Damage to Attacks",
    valueRanges: [
      {
        min: 24,
        max: 29,
      },
      {
        min: 34,
        max: 39,
      },
    ],
    rawAffix: "Adds `(24-29)`- `(34-39)`Fire Damage to Attacks",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds {0}- {1}Physical Damage to Attacks",
    valueRanges: [
      {
        min: 25,
        max: 30,
      },
      {
        min: 33,
        max: 38,
      },
    ],
    rawAffix: "Adds `(25-30)`- `(33-38)`Physical Damage to Attacks",
  },
  {
    equipmentTypeKey: "crossbow",
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds {0}- {1}Erosion Damage to Attacks",
    valueRanges: [
      {
        min: 26,
        max: 31,
      },
      {
        min: 32,
        max: 37,
      },
    ],
    rawAffix: "Adds `(26-31)`- `(32-37)`Erosion Damage to Attacks",
  },
] as const satisfies readonly BaseGearAffix[];

export type CrossbowBaseAffixAffix =
  (typeof CROSSBOW_BASE_AFFIX_AFFIXES)[number];
