import { BaseGearAffix } from "./types";

export const DAGGER_SUFFIX_AFFIXES = [
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Shadow Quantity +2\n+{0}% additional Shadow Damage",
    valueRanges: [
      {
        min: 10,
        max: 15,
      },
    ],
    rawAffix: "Shadow Quantity `+2`<> `+(10-15)`% additional Shadow Damage",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+{0}% chance to deal Double Damage",
    valueRanges: [
      {
        min: 41,
        max: 52,
      },
    ],
    rawAffix: "`+(41-52)`% chance to deal Double Damage",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+{0}% Focus Damage Enhancement",
    valueRanges: [
      {
        min: 48,
        max: 60,
      },
    ],
    rawAffix: "`+(48-60)`% Focus Damage Enhancement",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+{0}% additional damage against Frozen enemies",
    valueRanges: [
      {
        min: 54,
        max: 69,
      },
    ],
    rawAffix: "`+(54-69)`% additional damage against Frozen enemies",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Adds 23% of Main-Hand Weapon Damage to Base Wilt Damage",
    valueRanges: [],
    rawAffix: "Adds `23`% of Main-Hand Weapon Damage to Base Wilt Damage",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Shadow Quantity +2\n-5% additional Shadow Damage",
    valueRanges: [],
    rawAffix: "Shadow Quantity `+2`<> `-5`% additional Shadow Damage",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+{0}% chance to deal Double Damage",
    valueRanges: [
      {
        min: 29,
        max: 40,
      },
    ],
    rawAffix: "`+(29-40)`% chance to deal Double Damage",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+{0}% Focus Damage Enhancement",
    valueRanges: [
      {
        min: 35,
        max: 45,
      },
    ],
    rawAffix: "`+(35-45)`% Focus Damage Enhancement",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+{0}% additional damage against Frozen enemies",
    valueRanges: [
      {
        min: 38,
        max: 53,
      },
    ],
    rawAffix: "`+(38-53)`% additional damage against Frozen enemies",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Adds 19% of Main-Hand Weapon Damage to Base Wilt Damage",
    valueRanges: [],
    rawAffix: "Adds `19`% of Main-Hand Weapon Damage to Base Wilt Damage",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Critical Strike Rating",
    valueRanges: [
      {
        min: 166,
        max: 234,
      },
    ],
    rawAffix: "`+(166-234)`% Critical Strike Rating",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Attack and Cast Speed\n+{1}% Minion Attack and Cast Speed",
    valueRanges: [
      {
        min: 33,
        max: 47,
      },
      {
        min: 33,
        max: 47,
      },
    ],
    rawAffix:
      "`+(33-47)`% Attack and Cast Speed<> `+(33-47)`% Minion Attack and Cast Speed",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Attack Critical Strike Rating for this gear",
    valueRanges: [
      {
        min: 47,
        max: 64,
      },
    ],
    rawAffix: "`+(47-64)`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Focus Speed",
    valueRanges: [
      {
        min: 60,
        max: 70,
      },
    ],
    rawAffix: "`+(60-70)`% Focus Speed",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% chance to Multistrike",
    valueRanges: [
      {
        min: 74,
        max: 94,
      },
    ],
    rawAffix: "`+(74-94)`% chance to Multistrike",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Affliction Effect",
    valueRanges: [
      {
        min: 76,
        max: 98,
      },
    ],
    rawAffix: "`+(76-98)`% Affliction Effect",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Critical Strike Damage",
    valueRanges: [
      {
        min: 91,
        max: 117,
      },
    ],
    rawAffix: "`+(91-117)`% Critical Strike Damage",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Critical Strike Rating",
    valueRanges: [
      {
        min: 128,
        max: 180,
      },
    ],
    rawAffix: "`+(128-180)`% Critical Strike Rating",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Attack and Cast Speed\n+{1}% Minion Attack and Cast Speed",
    valueRanges: [
      {
        min: 26,
        max: 36,
      },
      {
        min: 26,
        max: 36,
      },
    ],
    rawAffix:
      "`+(26-36)`% Attack and Cast Speed<> `+(26-36)`% Minion Attack and Cast Speed",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Attack Critical Strike Rating for this gear",
    valueRanges: [
      {
        min: 36,
        max: 50,
      },
    ],
    rawAffix: "`+(36-50)`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Focus Speed",
    valueRanges: [
      {
        min: 45,
        max: 54,
      },
    ],
    rawAffix: "`+(45-54)`% Focus Speed",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Affliction Effect",
    valueRanges: [
      {
        min: 54,
        max: 75,
      },
    ],
    rawAffix: "`+(54-75)`% Affliction Effect",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% chance to Multistrike",
    valueRanges: [
      {
        min: 57,
        max: 72,
      },
    ],
    rawAffix: "`+(57-72)`% chance to Multistrike",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Critical Strike Damage",
    valueRanges: [
      {
        min: 64,
        max: 90,
      },
    ],
    rawAffix: "`+(64-90)`% Critical Strike Damage",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% Elemental Damage",
    valueRanges: [
      {
        min: 109,
        max: 140,
      },
    ],
    rawAffix: "`+(109-140)`% Elemental Damage",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% Erosion Damage",
    valueRanges: [
      {
        min: 109,
        max: 140,
      },
    ],
    rawAffix: "`+(109-140)`% Erosion Damage",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% Physical Damage",
    valueRanges: [
      {
        min: 109,
        max: 140,
      },
    ],
    rawAffix: "`+(109-140)`% Physical Damage",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% Energy Shield Regain",
    valueRanges: [
      {
        min: 19,
        max: 23,
      },
    ],
    rawAffix: "`+(19-23)`% Energy Shield Regain",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% Life Regain",
    valueRanges: [
      {
        min: 19,
        max: 23,
      },
    ],
    rawAffix: "`+(19-23)`% Life Regain",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% gear Attack Speed",
    valueRanges: [
      {
        min: 29,
        max: 41,
      },
    ],
    rawAffix: "`+(29-41)`% gear Attack Speed",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% Energy Shield Regain",
    valueRanges: [
      {
        min: 14,
        max: 18,
      },
    ],
    rawAffix: "`+(14-18)`% Energy Shield Regain",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% Life Regain",
    valueRanges: [
      {
        min: 14,
        max: 18,
      },
    ],
    rawAffix: "`+(14-18)`% Life Regain",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% gear Attack Speed",
    valueRanges: [
      {
        min: 23,
        max: 32,
      },
    ],
    rawAffix: "`+(23-32)`% gear Attack Speed",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% Elemental Damage",
    valueRanges: [
      {
        min: 77,
        max: 108,
      },
    ],
    rawAffix: "`+(77-108)`% Elemental Damage",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% Erosion Damage",
    valueRanges: [
      {
        min: 77,
        max: 108,
      },
    ],
    rawAffix: "`+(77-108)`% Erosion Damage",
  },
  {
    equipmentTypeKey: "dagger",
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% Physical Damage",
    valueRanges: [
      {
        min: 77,
        max: 108,
      },
    ],
    rawAffix: "`+(77-108)`% Physical Damage",
  },
] as const satisfies readonly BaseGearAffix[];

export type DaggerSuffixAffix = (typeof DAGGER_SUFFIX_AFFIXES)[number];
