import { BaseGearAffix } from "./types";

export const HELMET_STR_PREFIX_AFFIXES = [
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      "-45% additional Damage Over Time taken when having at least 50000Armor",
    valueRanges: [],
    rawAffix:
      "`-45`% additional Damage Over Time taken when having at least `50000`Armor",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "{0}% additional Damage dealt by Nearby enemies",
    valueRanges: [
      {
        min: -20,
        max: -16,
      },
    ],
    rawAffix: "`(-20--16)`% additional Damage dealt by Nearby enemies",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "{0}% of damage is taken from Mana before life",
    valueRanges: [
      {
        min: 21,
        max: 26,
      },
    ],
    rawAffix: "`(21-26)`% of damage is taken from Mana before life",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+{0}% Sealed Mana Compensation",
    valueRanges: [
      {
        min: 21,
        max: 26,
      },
    ],
    rawAffix: "`+(21-26)`% Sealed Mana Compensation",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      "+1Max Spell Burst\n+10% additional Hit Damage for skills cast by Spell Burst",
    valueRanges: [],
    rawAffix:
      "`+1`Max Spell Burst<> `+10`% additional Hit Damage for skills cast by Spell Burst",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Converts {0}% of Physical Damage taken to Fire Damage",
    valueRanges: [
      {
        min: 16,
        max: 20,
      },
    ],
    rawAffix: "Converts `(16-20)`% of Physical Damage taken to Fire Damage",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Converts {0}% of Erosion Damage taken to Fire Damage",
    valueRanges: [
      {
        min: 36,
        max: 45,
      },
    ],
    rawAffix: "Converts `(36-45)`% of Erosion Damage taken to Fire Damage",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Terra Charge Stacks +1\n+30% Terra Charge Recovery Speed",
    valueRanges: [],
    rawAffix:
      "Max Terra Charge Stacks `+1`<> `+30`% Terra Charge Recovery Speed",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      "-40% additional Damage Over Time taken when having at least 50000Armor",
    valueRanges: [],
    rawAffix:
      "`-40`% additional Damage Over Time taken when having at least `50000`Armor",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "{0}% additional Damage dealt by Nearby enemies",
    valueRanges: [
      {
        min: -15,
        max: -12,
      },
    ],
    rawAffix: "`(-15--12)`% additional Damage dealt by Nearby enemies",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "{0}% of damage is taken from Mana before life",
    valueRanges: [
      {
        min: 15,
        max: 20,
      },
    ],
    rawAffix: "`(15-20)`% of damage is taken from Mana before life",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+{0}% Sealed Mana Compensation",
    valueRanges: [
      {
        min: 15,
        max: 20,
      },
    ],
    rawAffix: "`+(15-20)`% Sealed Mana Compensation",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+1Max Spell Burst",
    valueRanges: [],
    rawAffix: "`+1`Max Spell Burst",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Converts {0}% of Physical Damage taken to Fire Damage",
    valueRanges: [
      {
        min: 12,
        max: 15,
      },
    ],
    rawAffix: "Converts `(12-15)`% of Physical Damage taken to Fire Damage",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Converts {0}% of Erosion Damage taken to Fire Damage",
    valueRanges: [
      {
        min: 27,
        max: 35,
      },
    ],
    rawAffix: "Converts `(27-35)`% of Erosion Damage taken to Fire Damage",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Terra Charge Stacks +1",
    valueRanges: [],
    rawAffix: "Max Terra Charge Stacks `+1`",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Block Ratio",
    valueRanges: [
      {
        min: 14,
        max: 17,
      },
    ],
    rawAffix: "`+(14-17)`% Block Ratio",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Projectile Speed",
    valueRanges: [
      {
        min: 46,
        max: 59,
      },
    ],
    rawAffix: "`+(46-59)`% Projectile Speed",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% chance to gain 1 stack of Tenacity Blessing on defeat",
    valueRanges: [
      {
        min: 51,
        max: 65,
      },
    ],
    rawAffix:
      "`+(51-65)`% chance to gain 1 stack of Tenacity Blessing on defeat",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}Dexterity",
    valueRanges: [
      {
        min: 61,
        max: 78,
      },
    ],
    rawAffix: "`+(61-78)`Dexterity",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}Intelligence",
    valueRanges: [
      {
        min: 61,
        max: 78,
      },
    ],
    rawAffix: "`+(61-78)`Intelligence",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}Strength",
    valueRanges: [
      {
        min: 61,
        max: 78,
      },
    ],
    rawAffix: "`+(61-78)`Strength",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Barrier Shield",
    valueRanges: [
      {
        min: 61,
        max: 78,
      },
    ],
    rawAffix: "`+(61-78)`% Barrier Shield",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Block Ratio",
    valueRanges: [
      {
        min: 10,
        max: 13,
      },
    ],
    rawAffix: "`+(10-13)`% Block Ratio",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Projectile Speed",
    valueRanges: [
      {
        min: 33,
        max: 45,
      },
    ],
    rawAffix: "`+(33-45)`% Projectile Speed",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% chance to gain 1 stack of Tenacity Blessing on defeat",
    valueRanges: [
      {
        min: 37,
        max: 50,
      },
    ],
    rawAffix:
      "`+(37-50)`% chance to gain 1 stack of Tenacity Blessing on defeat",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}Dexterity",
    valueRanges: [
      {
        min: 43,
        max: 60,
      },
    ],
    rawAffix: "`+(43-60)`Dexterity",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}Intelligence",
    valueRanges: [
      {
        min: 43,
        max: 60,
      },
    ],
    rawAffix: "`+(43-60)`Intelligence",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}Strength",
    valueRanges: [
      {
        min: 43,
        max: 60,
      },
    ],
    rawAffix: "`+(43-60)`Strength",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Barrier Shield",
    valueRanges: [
      {
        min: 43,
        max: 60,
      },
    ],
    rawAffix: "`+(43-60)`% Barrier Shield",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}Max Mana",
    valueRanges: [
      {
        min: 121,
        max: 156,
      },
    ],
    rawAffix: "`+(121-156)`Max Mana",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}Max Life",
    valueRanges: [
      {
        min: 221,
        max: 286,
      },
    ],
    rawAffix: "`+(221-286)`Max Life",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}Gear Armor",
    valueRanges: [
      {
        min: 2622,
        max: 3744,
      },
    ],
    rawAffix: "`+(2622-3744)`Gear Armor",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% damage",
    valueRanges: [
      {
        min: 73,
        max: 94,
      },
    ],
    rawAffix: "`+(73-94)`% damage",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% Minion Damage",
    valueRanges: [
      {
        min: 73,
        max: 94,
      },
    ],
    rawAffix: "`+(73-94)`% Minion Damage",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}Max Life",
    valueRanges: [
      {
        min: 154,
        max: 220,
      },
    ],
    rawAffix: "`+(154-220)`Max Life",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}Gear Armor",
    valueRanges: [
      {
        min: 2017,
        max: 2880,
      },
    ],
    rawAffix: "`+(2017-2880)`Gear Armor",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% damage",
    valueRanges: [
      {
        min: 51,
        max: 72,
      },
    ],
    rawAffix: "`+(51-72)`% damage",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% Minion Damage",
    valueRanges: [
      {
        min: 51,
        max: 72,
      },
    ],
    rawAffix: "`+(51-72)`% Minion Damage",
  },
  {
    equipmentTypeKey: "helmet_str",
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}Max Mana",
    valueRanges: [
      {
        min: 85,
        max: 120,
      },
    ],
    rawAffix: "`+(85-120)`Max Mana",
  },
] as const satisfies readonly BaseGearAffix[];

export type HelmetStrPrefixAffix = (typeof HELMET_STR_PREFIX_AFFIXES)[number];
