import { BaseGearAffix } from "./types";

export const NECKLACE_PREFIX_AFFIXES = [
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "[Beacon] +2Max Spell Burst",
    valueRanges: [],
    rawAffix: "[Beacon] `+2`Max Spell Burst",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Multistrikes deal {0}% increasing damage",
    valueRanges: [
      {
        min: 36,
        max: 52,
      },
    ],
    rawAffix: "Multistrikes deal `(36-52)`% increasing damage",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+{0}% Deterioration Damage",
    valueRanges: [
      {
        min: 51,
        max: 65,
      },
    ],
    rawAffix: "`+(51-65)`% Deterioration Damage",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+3Active Skill Level",
    valueRanges: [],
    rawAffix: "`+3`Active Skill Level",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+3Minion Skill Level",
    valueRanges: [],
    rawAffix: "`+3`Minion Skill Level",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Have Fervor\n+5% additional damage",
    valueRanges: [],
    rawAffix: "Have Fervor<> `+5`% additional damage",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Multistrikes deal {0}% increasing damage",
    valueRanges: [
      {
        min: 28,
        max: 40,
      },
    ],
    rawAffix: "Multistrikes deal `(28-40)`% increasing damage",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+{0}Active Skill Level",
    valueRanges: [
      {
        min: 1,
        max: 2,
      },
    ],
    rawAffix: "`+(1-2)`Active Skill Level",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+{0}% Deterioration Damage",
    valueRanges: [
      {
        min: 36,
        max: 50,
      },
    ],
    rawAffix: "`+(36-50)`% Deterioration Damage",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+1Max Spell Burst",
    valueRanges: [],
    rawAffix: "`+1`Max Spell Burst",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+2Minion Skill Level",
    valueRanges: [],
    rawAffix: "`+2`Minion Skill Level",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Have Fervor",
    valueRanges: [],
    rawAffix: "Have Fervor",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Defense",
    valueRanges: [
      {
        min: 21,
        max: 26,
      },
    ],
    rawAffix: "`+(21-26)`% Defense",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Sealed Mana Compensation for Energy Fortress",
    valueRanges: [
      {
        min: 31,
        max: 39,
      },
    ],
    rawAffix: "`+(31-39)`% Sealed Mana Compensation for Energy Fortress",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Sealed Mana Compensation for Nimbleness",
    valueRanges: [
      {
        min: 31,
        max: 39,
      },
    ],
    rawAffix: "`+(31-39)`% Sealed Mana Compensation for Nimbleness",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Sealed Mana Compensation for Steadfast",
    valueRanges: [
      {
        min: 31,
        max: 39,
      },
    ],
    rawAffix: "`+(31-39)`% Sealed Mana Compensation for Steadfast",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Deterioration Chance",
    valueRanges: [
      {
        min: 33,
        max: 42,
      },
    ],
    rawAffix: "`+(33-42)`% Deterioration Chance",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}initial Growth for Spirit Magi",
    valueRanges: [
      {
        min: 49,
        max: 62,
      },
    ],
    rawAffix: "`+(49-62)`initial Growth for Spirit Magi",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}Dexterity",
    valueRanges: [
      {
        min: 61,
        max: 78,
      },
    ],
    rawAffix: "`+(61-78)`Dexterity",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}Intelligence",
    valueRanges: [
      {
        min: 61,
        max: 78,
      },
    ],
    rawAffix: "`+(61-78)`Intelligence",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}Strength",
    valueRanges: [
      {
        min: 61,
        max: 78,
      },
    ],
    rawAffix: "`+(61-78)`Strength",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      "Gains Attack Aggression when casting an Attack Skill\n+{0}% Attack Aggression Effect",
    valueRanges: [
      {
        min: 40,
        max: 60,
      },
    ],
    rawAffix:
      "Gains Attack Aggression when casting an Attack Skill<> `+(40-60)`% Attack Aggression Effect",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      "Gains Spell Aggression when casting a Spell Skill\n+{0}% Spell Aggression Effect",
    valueRanges: [
      {
        min: 40,
        max: 60,
      },
    ],
    rawAffix:
      "Gains Spell Aggression when casting a Spell Skill<> `+(40-60)`% Spell Aggression Effect",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Defense",
    valueRanges: [
      {
        min: 15,
        max: 20,
      },
    ],
    rawAffix: "`+(15-20)`% Defense",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Sealed Mana Compensation for Energy Fortress",
    valueRanges: [
      {
        min: 22,
        max: 30,
      },
    ],
    rawAffix: "`+(22-30)`% Sealed Mana Compensation for Energy Fortress",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Sealed Mana Compensation for Nimbleness",
    valueRanges: [
      {
        min: 22,
        max: 30,
      },
    ],
    rawAffix: "`+(22-30)`% Sealed Mana Compensation for Nimbleness",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Sealed Mana Compensation for Steadfast",
    valueRanges: [
      {
        min: 22,
        max: 30,
      },
    ],
    rawAffix: "`+(22-30)`% Sealed Mana Compensation for Steadfast",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Deterioration Chance",
    valueRanges: [
      {
        min: 23,
        max: 32,
      },
    ],
    rawAffix: "`+(23-32)`% Deterioration Chance",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}initial Growth for Spirit Magi",
    valueRanges: [
      {
        min: 35,
        max: 48,
      },
    ],
    rawAffix: "`+(35-48)`initial Growth for Spirit Magi",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}Dexterity",
    valueRanges: [
      {
        min: 43,
        max: 60,
      },
    ],
    rawAffix: "`+(43-60)`Dexterity",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}Intelligence",
    valueRanges: [
      {
        min: 43,
        max: 60,
      },
    ],
    rawAffix: "`+(43-60)`Intelligence",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}Strength",
    valueRanges: [
      {
        min: 43,
        max: 60,
      },
    ],
    rawAffix: "`+(43-60)`Strength",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      "Gains Attack Aggression when casting an Attack Skill\n+{0}% Attack Aggression Effect",
    valueRanges: [
      {
        min: 10,
        max: 30,
      },
    ],
    rawAffix:
      "Gains Attack Aggression when casting an Attack Skill<> `+(10-30)`% Attack Aggression Effect",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      "Gains Spell Aggression when casting a Spell Skill\n+{0}% Spell Aggression Effect",
    valueRanges: [
      {
        min: 10,
        max: 30,
      },
    ],
    rawAffix:
      "Gains Spell Aggression when casting a Spell Skill<> `+(10-30)`% Spell Aggression Effect",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}Max Mana",
    valueRanges: [
      {
        min: 121,
        max: 156,
      },
    ],
    rawAffix: "`+(121-156)`Max Mana",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}Max Life",
    valueRanges: [
      {
        min: 221,
        max: 286,
      },
    ],
    rawAffix: "`+(221-286)`Max Life",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}Max Energy Shield",
    valueRanges: [
      {
        min: 319,
        max: 455,
      },
    ],
    rawAffix: "`+(319-455)`Max Energy Shield",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% Armor",
    valueRanges: [
      {
        min: 37,
        max: 47,
      },
    ],
    rawAffix: "`+(37-47)`% Armor",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% Evasion",
    valueRanges: [
      {
        min: 37,
        max: 47,
      },
    ],
    rawAffix: "`+(37-47)`% Evasion",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% Minion Damage",
    valueRanges: [
      {
        min: 66,
        max: 94,
      },
    ],
    rawAffix: "`+(66-94)`% Minion Damage",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% damage",
    valueRanges: [
      {
        min: 73,
        max: 94,
      },
    ],
    rawAffix: "`+(73-94)`% damage",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}Max Life",
    valueRanges: [
      {
        min: 155,
        max: 220,
      },
    ],
    rawAffix: "`+(155-220)`Max Life",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}Max Energy Shield",
    valueRanges: [
      {
        min: 245,
        max: 350,
      },
    ],
    rawAffix: "`+(245-350)`Max Energy Shield",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% Armor",
    valueRanges: [
      {
        min: 27,
        max: 36,
      },
    ],
    rawAffix: "`+(27-36)`% Armor",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% Evasion",
    valueRanges: [
      {
        min: 27,
        max: 36,
      },
    ],
    rawAffix: "`+(27-36)`% Evasion",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% damage",
    valueRanges: [
      {
        min: 51,
        max: 72,
      },
    ],
    rawAffix: "`+(51-72)`% damage",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% Minion Damage",
    valueRanges: [
      {
        min: 51,
        max: 72,
      },
    ],
    rawAffix: "`+(51-72)`% Minion Damage",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}Max Mana",
    valueRanges: [
      {
        min: 85,
        max: 120,
      },
    ],
    rawAffix: "`+(85-120)`Max Mana",
  },
] as const satisfies readonly BaseGearAffix[];

export type NecklacePrefixAffix = (typeof NECKLACE_PREFIX_AFFIXES)[number];
