import { BaseGearAffix } from "./types";

export const NECKLACE_SUFFIX_AFFIXES = [
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+{0}% Sealed Mana Compensation",
    valueRanges: [
      {
        min: 21,
        max: 26,
      },
    ],
    rawAffix: "`+(21-26)`% Sealed Mana Compensation",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+{0}% Aura Effect",
    valueRanges: [
      {
        min: 21,
        max: 26,
      },
    ],
    rawAffix: "`+(21-26)`% Aura Effect",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+{0}% additional Deterioration Duration",
    valueRanges: [
      {
        min: 33,
        max: 42,
      },
    ],
    rawAffix: "`+(33-42)`% additional Deterioration Duration",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+{0}% Freeze Duration",
    valueRanges: [
      {
        min: 37,
        max: 54,
      },
    ],
    rawAffix: "`+(37-54)`% Freeze Duration",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+{0}% damage per stack of any Blessing",
    valueRanges: [
      {
        min: 7,
        max: 8,
      },
    ],
    rawAffix: "`+(7-8)`% damage per stack of any Blessing",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+1% damage per 8stats",
    valueRanges: [],
    rawAffix: "`+1`% damage per `8`stats",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+{0}% Sealed Mana Compensation",
    valueRanges: [
      {
        min: 15,
        max: 20,
      },
    ],
    rawAffix: "`+(15-20)`% Sealed Mana Compensation",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+{0}% Aura Effect",
    valueRanges: [
      {
        min: 15,
        max: 20,
      },
    ],
    rawAffix: "`+(15-20)`% Aura Effect",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+{0}% additional Deterioration Duration",
    valueRanges: [
      {
        min: 23,
        max: 32,
      },
    ],
    rawAffix: "`+(23-32)`% additional Deterioration Duration",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+{0}% Freeze Duration",
    valueRanges: [
      {
        min: 28,
        max: 36,
      },
    ],
    rawAffix: "`+(28-36)`% Freeze Duration",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+{0}% damage per stack of any Blessing",
    valueRanges: [
      {
        min: 5,
        max: 6,
      },
    ],
    rawAffix: "`+(5-6)`% damage per stack of any Blessing",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+1% damage per 12stats",
    valueRanges: [],
    rawAffix: "`+1`% damage per `12`stats",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Elemental Resistance",
    valueRanges: [
      {
        min: 11,
        max: 13,
      },
    ],
    rawAffix: "`+(11-13)`% Elemental Resistance",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% all stats",
    valueRanges: [
      {
        min: 11,
        max: 13,
      },
    ],
    rawAffix: "`+(11-13)`% all stats",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Blessing Duration",
    valueRanges: [
      {
        min: 19,
        max: 23,
      },
    ],
    rawAffix: "`+(19-23)`% Blessing Duration",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Attack and Cast Speed\n+{1}% Minion Attack and Cast Speed",
    valueRanges: [
      {
        min: 25,
        max: 31,
      },
      {
        min: 25,
        max: 31,
      },
    ],
    rawAffix:
      "`+(25-31)`% Attack and Cast Speed<> `+(25-31)`% Minion Attack and Cast Speed",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}% Critical Strike Damage",
    valueRanges: [
      {
        min: 61,
        max: 78,
      },
    ],
    rawAffix: "`+(61-78)`% Critical Strike Damage",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      "100% chance to gain a Barrier for every 5m you move\n+25% Barrier Shield",
    valueRanges: [],
    rawAffix:
      "`100`% chance to gain a Barrier for every `5`m you move<> `+25`% Barrier Shield",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "80% chance to gain 1charge stacks when using a Terra Skill",
    valueRanges: [],
    rawAffix: "`80`% chance to gain `1`charge stacks when using a Terra Skill",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Blessing Duration",
    valueRanges: [
      {
        min: 14,
        max: 18,
      },
    ],
    rawAffix: "`+(14-18)`% Blessing Duration",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Attack and Cast Speed\n+{1}% Minion Attack and Cast Speed",
    valueRanges: [
      {
        min: 18,
        max: 24,
      },
      {
        min: 18,
        max: 24,
      },
    ],
    rawAffix:
      "`+(18-24)`% Attack and Cast Speed<> `+(18-24)`% Minion Attack and Cast Speed",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Critical Strike Damage",
    valueRanges: [
      {
        min: 42,
        max: 60,
      },
    ],
    rawAffix: "`+(42-60)`% Critical Strike Damage",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% Elemental Resistance",
    valueRanges: [
      {
        min: 8,
        max: 10,
      },
    ],
    rawAffix: "`+(8-10)`% Elemental Resistance",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}% all stats",
    valueRanges: [
      {
        min: 8,
        max: 10,
      },
    ],
    rawAffix: "`+(8-10)`% all stats",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "100% chance to gain a Barrier for every 5m you move",
    valueRanges: [],
    rawAffix: "`100`% chance to gain a Barrier for every `5`m you move",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "60% chance to gain 1charge stacks when using a Terra Skill",
    valueRanges: [],
    rawAffix: "`60`% chance to gain `1`charge stacks when using a Terra Skill",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% Cold Resistance",
    valueRanges: [
      {
        min: 25,
        max: 35,
      },
    ],
    rawAffix: "`+(25-35)`% Cold Resistance",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% Erosion Resistance",
    valueRanges: [
      {
        min: 25,
        max: 35,
      },
    ],
    rawAffix: "`+(25-35)`% Erosion Resistance",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% Fire Resistance",
    valueRanges: [
      {
        min: 25,
        max: 35,
      },
    ],
    rawAffix: "`+(25-35)`% Fire Resistance",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% Lightning Resistance",
    valueRanges: [
      {
        min: 25,
        max: 35,
      },
    ],
    rawAffix: "`+(25-35)`% Lightning Resistance",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% Projectile Speed",
    valueRanges: [
      {
        min: 46,
        max: 59,
      },
    ],
    rawAffix: "`+(46-59)`% Projectile Speed",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% Cold Resistance",
    valueRanges: [
      {
        min: 19,
        max: 27,
      },
    ],
    rawAffix: "`+(19-27)`% Cold Resistance",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% Erosion Resistance",
    valueRanges: [
      {
        min: 19,
        max: 27,
      },
    ],
    rawAffix: "`+(19-27)`% Erosion Resistance",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% Fire Resistance",
    valueRanges: [
      {
        min: 19,
        max: 27,
      },
    ],
    rawAffix: "`+(19-27)`% Fire Resistance",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% Lightning Resistance",
    valueRanges: [
      {
        min: 19,
        max: 27,
      },
    ],
    rawAffix: "`+(19-27)`% Lightning Resistance",
  },
  {
    equipmentTypeKey: "necklace",
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% Projectile Speed",
    valueRanges: [
      {
        min: 33,
        max: 45,
      },
    ],
    rawAffix: "`+(33-45)`% Projectile Speed",
  },
] as const satisfies readonly BaseGearAffix[];

export type NecklaceSuffixAffix = (typeof NECKLACE_SUFFIX_AFFIXES)[number];
