import { BaseGearAffix } from "./types";

export const RING_BASE_STATS_AFFIXES = [
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "",
    valueRanges: [],
    rawAffix: "",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+11% Cold Resistance",
    valueRanges: [],
    rawAffix: "`+11`% Cold Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+11% Erosion Resistance",
    valueRanges: [],
    rawAffix: "`+11`% Erosion Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+11% Fire Resistance",
    valueRanges: [],
    rawAffix: "`+11`% Fire Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+11% Lightning Resistance",
    valueRanges: [],
    rawAffix: "`+11`% Lightning Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+12% Cold Resistance",
    valueRanges: [],
    rawAffix: "`+12`% Cold Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+12% Erosion Resistance",
    valueRanges: [],
    rawAffix: "`+12`% Erosion Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+12% Fire Resistance",
    valueRanges: [],
    rawAffix: "`+12`% Fire Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+12% Lightning Resistance",
    valueRanges: [],
    rawAffix: "`+12`% Lightning Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+3% Cold Resistance",
    valueRanges: [],
    rawAffix: "`+3`% Cold Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+3% Erosion Resistance",
    valueRanges: [],
    rawAffix: "`+3`% Erosion Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+3% Fire Resistance",
    valueRanges: [],
    rawAffix: "`+3`% Fire Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+3% Lightning Resistance",
    valueRanges: [],
    rawAffix: "`+3`% Lightning Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+4% Cold Resistance",
    valueRanges: [],
    rawAffix: "`+4`% Cold Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+4% Erosion Resistance",
    valueRanges: [],
    rawAffix: "`+4`% Erosion Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+4% Fire Resistance",
    valueRanges: [],
    rawAffix: "`+4`% Fire Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+4% Lightning Resistance",
    valueRanges: [],
    rawAffix: "`+4`% Lightning Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+6% Cold Resistance",
    valueRanges: [],
    rawAffix: "`+6`% Cold Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+6% Erosion Resistance",
    valueRanges: [],
    rawAffix: "`+6`% Erosion Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+6% Fire Resistance",
    valueRanges: [],
    rawAffix: "`+6`% Fire Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+6% Lightning Resistance",
    valueRanges: [],
    rawAffix: "`+6`% Lightning Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+9% Cold Resistance",
    valueRanges: [],
    rawAffix: "`+9`% Cold Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+9% Erosion Resistance",
    valueRanges: [],
    rawAffix: "`+9`% Erosion Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+9% Fire Resistance",
    valueRanges: [],
    rawAffix: "`+9`% Fire Resistance",
  },
  {
    equipmentTypeKey: "ring",
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "+9% Lightning Resistance",
    valueRanges: [],
    rawAffix: "`+9`% Lightning Resistance",
  },
] as const satisfies readonly BaseGearAffix[];

export type RingBaseStatsAffix = (typeof RING_BASE_STATS_AFFIXES)[number];
