import { BaseGearAffix } from "./types";

export const ROD_TOWER_SEQUENCE_AFFIXES = [
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "+ 10Command per second",
    valueRanges: [],
    rawAffix: "+ `10`Command per second",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "-80Minion Critical Strike Rating\n+200% Minion Critical Strike Damage",
    valueRanges: [],
    rawAffix:
      "`-80`Minion Critical Strike Rating<> `+200`% Minion Critical Strike Damage",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "+120% Radical Order Aura Effect\n-20% additional Radical Order Sealed Mana Compensation",
    valueRanges: [],
    rawAffix:
      "`+120`% Radical Order Aura Effect<> `-20`% additional Radical Order Sealed Mana Compensation",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "+80initial Growth for Spirit Magi",
    valueRanges: [],
    rawAffix: "`+80`initial Growth for Spirit Magi",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "The Main Skill is supported by a Lv. 25Servant Damage",
    valueRanges: [],
    rawAffix: "The Main Skill is supported by a Lv. `25`Servant Damage",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "Triggers Lv. 10Entangled Pain Curse and Timid Curse when a Minion deals damage. Cooldown: 1s\nMinions can cast 1additional Curse(s)",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. `10`Entangled Pain Curse and Timid Curse when a Minion deals damage. Cooldown: `1`s<> Minions can cast `1`additional Curse(s)",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "Triggers Lv. 20Dark Gate when moving. Interval: 4s",
    valueRanges: [],
    rawAffix: "Triggers Lv. `20`Dark Gate when moving. Interval: `4`s",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "When Minions deal damage, inflicts Fire Infiltration . Interval for each enemy: 1s\nWhen Minions deal damage, inflicts Lightning Infiltration . Interval for each enemy: 1s\nWhen Minions deal damage, inflicts Cold Infiltration . Interval for each enemy: 1s",
    valueRanges: [],
    rawAffix:
      "When Minions deal damage, inflicts Fire Infiltration . Interval for each enemy: `1`s<> When Minions deal damage, inflicts Lightning Infiltration . Interval for each enemy: `1`s<> When Minions deal damage, inflicts Cold Infiltration . Interval for each enemy: `1`s",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+16% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix: "`+16`% Minion Attack and Cast Speed",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+40% Minion Critical Strike Damage",
    valueRanges: [],
    rawAffix: "`+40`% Minion Critical Strike Damage",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+55Minion Critical Strike Rating",
    valueRanges: [],
    rawAffix: "`+55`Minion Critical Strike Rating",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+6% Armor DMG Mitigation Penetration for Minions",
    valueRanges: [],
    rawAffix: "`+6`% Armor DMG Mitigation Penetration for Minions",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+8% all stats",
    valueRanges: [],
    rawAffix: "`+8`% all stats",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+8% additional Minion Damage",
    valueRanges: [],
    rawAffix: "`+8`% additional Minion Damage",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+8% Cold Penetration for Minions",
    valueRanges: [],
    rawAffix: "`+8`% Cold Penetration for Minions",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+8% Erosion Penetration for Minions",
    valueRanges: [],
    rawAffix: "`+8`% Erosion Penetration for Minions",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+8% Lightning Penetration for Minions",
    valueRanges: [],
    rawAffix: "`+8`% Lightning Penetration for Minions",
  },
  {
    equipmentTypeKey: "rod",
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "+8% Minion Fire Penetration",
    valueRanges: [],
    rawAffix: "`+8`% Minion Fire Penetration",
  },
] as const satisfies readonly BaseGearAffix[];

export type RodTowerSequenceAffix = (typeof ROD_TOWER_SEQUENCE_AFFIXES)[number];
