import { BaseGearAffix } from "./types";

export const TIN_STAFF_BASE_STATS_AFFIXES = [
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
  {
    equipmentTypeKey: "tin_staff",
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "500Critical Strike Rating\n1.2Attack Speed",
    valueRanges: [],
    rawAffix: "`500`Critical Strike Rating<> `1.2`Attack Speed",
  },
] as const satisfies readonly BaseGearAffix[];

export type TinStaffBaseStatsAffix =
  (typeof TIN_STAFF_BASE_STATS_AFFIXES)[number];
