import { BaseGearAffix } from "./types";

export const WAND_PREFIX_AFFIXES = [
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+{0}% Armor DMG Mitigation Penetration",
    valueRanges: [
      {
        min: 26,
        max: 36,
      },
    ],
    rawAffix: "`+(26-36)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+{0}% Elemental and Erosion Resistance Penetration",
    valueRanges: [
      {
        min: 28,
        max: 39,
      },
    ],
    rawAffix: "`+(28-39)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+{0}Spell Skill Level",
    valueRanges: [
      {
        min: 3,
        max: 4,
      },
    ],
    rawAffix: "`+(3-4)`Spell Skill Level",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+2Jumps\n+{0}% additional damage",
    valueRanges: [
      {
        min: 12,
        max: 16,
      },
    ],
    rawAffix: "`+2`Jumps<> `+(12-16)`% additional damage",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Terra Charge Stacks +3",
    valueRanges: [],
    rawAffix: "Max Terra Charge Stacks `+3`",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+{0}% Armor DMG Mitigation Penetration",
    valueRanges: [
      {
        min: 18,
        max: 25,
      },
    ],
    rawAffix: "`+(18-25)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+{0}% Elemental and Erosion Resistance Penetration",
    valueRanges: [
      {
        min: 22,
        max: 30,
      },
    ],
    rawAffix: "`+(22-30)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+2Jumps\n+{0}% additional damage",
    valueRanges: [
      {
        min: 8,
        max: 10,
      },
    ],
    rawAffix: "`+2`Jumps<> `+(8-10)`% additional damage",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+3Spell Skill Level",
    valueRanges: [],
    rawAffix: "`+3`Spell Skill Level",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Terra Charge Stacks +2",
    valueRanges: [],
    rawAffix: "Max Terra Charge Stacks `+2`",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}Cold Skill Level",
    valueRanges: [
      {
        min: 2,
        max: 3,
      },
    ],
    rawAffix: "`+(2-3)`Cold Skill Level",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}Erosion Skill Level",
    valueRanges: [
      {
        min: 2,
        max: 3,
      },
    ],
    rawAffix: "`+(2-3)`Erosion Skill Level",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}Fire Skill Level",
    valueRanges: [
      {
        min: 2,
        max: 3,
      },
    ],
    rawAffix: "`+(2-3)`Fire Skill Level",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}Lightning Skill Level",
    valueRanges: [
      {
        min: 2,
        max: 3,
      },
    ],
    rawAffix: "`+(2-3)`Lightning Skill Level",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}Physical Skill Level",
    valueRanges: [
      {
        min: 2,
        max: 3,
      },
    ],
    rawAffix: "`+(2-3)`Physical Skill Level",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}Dexterity",
    valueRanges: [
      {
        min: 91,
        max: 117,
      },
    ],
    rawAffix: "`+(91-117)`Dexterity",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}Intelligence",
    valueRanges: [
      {
        min: 91,
        max: 117,
      },
    ],
    rawAffix: "`+(91-117)`Intelligence",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "+{0}Strength",
    valueRanges: [
      {
        min: 91,
        max: 117,
      },
    ],
    rawAffix: "`+(91-117)`Strength",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}Dexterity",
    valueRanges: [
      {
        min: 64,
        max: 90,
      },
    ],
    rawAffix: "`+(64-90)`Dexterity",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}Intelligence",
    valueRanges: [
      {
        min: 64,
        max: 90,
      },
    ],
    rawAffix: "`+(64-90)`Intelligence",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+{0}Strength",
    valueRanges: [
      {
        min: 64,
        max: 90,
      },
    ],
    rawAffix: "`+(64-90)`Strength",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+2Cold Skill Level",
    valueRanges: [],
    rawAffix: "`+2`Cold Skill Level",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+2Erosion Skill Level",
    valueRanges: [],
    rawAffix: "`+2`Erosion Skill Level",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+2Fire Skill Level",
    valueRanges: [],
    rawAffix: "`+2`Fire Skill Level",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+2Lightning Skill Level",
    valueRanges: [],
    rawAffix: "`+2`Lightning Skill Level",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "+2Physical Skill Level",
    valueRanges: [],
    rawAffix: "`+2`Physical Skill Level",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}% Spell Damage",
    valueRanges: [
      {
        min: 109,
        max: 140,
      },
    ],
    rawAffix: "`+(109-140)`% Spell Damage",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "+{0}Max Mana",
    valueRanges: [
      {
        min: 181,
        max: 234,
      },
    ],
    rawAffix: "`+(181-234)`Max Mana",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds {0}- {1}Fire Damage to Spells",
    valueRanges: [
      {
        min: 82,
        max: 84,
      },
      {
        min: 106,
        max: 113,
      },
    ],
    rawAffix: "Adds `(82-84)`- `(106-113)`Fire Damage to Spells",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds {0}- {1}Cold Damage to Spells",
    valueRanges: [
      {
        min: 83,
        max: 85,
      },
      {
        min: 110,
        max: 112,
      },
    ],
    rawAffix: "Adds `(83-85)`- `(110-112)`Cold Damage to Spells",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds {0}- {1}Erosion Damage to Spells",
    valueRanges: [
      {
        min: 87,
        max: 89,
      },
      {
        min: 106,
        max: 108,
      },
    ],
    rawAffix: "Adds `(87-89)`- `(106-108)`Erosion Damage to Spells",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds {0}- {1}Physical Damage to Spells",
    valueRanges: [
      {
        min: 87,
        max: 89,
      },
      {
        min: 106,
        max: 108,
      },
    ],
    rawAffix: "Adds `(87-89)`- `(106-108)`Physical Damage to Spells",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds {0}- {1}Lightning Damage to Spells",
    valueRanges: [
      {
        min: 9,
        max: 11,
      },
      {
        min: 184,
        max: 186,
      },
    ],
    rawAffix: "Adds `(9-11)`- `(184-186)`Lightning Damage to Spells",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}Max Mana",
    valueRanges: [
      {
        min: 127,
        max: 180,
      },
    ],
    rawAffix: "`+(127-180)`Max Mana",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "+{0}% Spell Damage",
    valueRanges: [
      {
        min: 77,
        max: 108,
      },
    ],
    rawAffix: "`+(77-108)`% Spell Damage",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds {0}- {1}Fire Damage to Spells",
    valueRanges: [
      {
        min: 63,
        max: 65,
      },
      {
        min: 82,
        max: 87,
      },
    ],
    rawAffix: "Adds `(63-65)`- `(82-87)`Fire Damage to Spells",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds {0}- {1}Cold Damage to Spells",
    valueRanges: [
      {
        min: 64,
        max: 66,
      },
      {
        min: 85,
        max: 87,
      },
    ],
    rawAffix: "Adds `(64-66)`- `(85-87)`Cold Damage to Spells",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds {0}- {1}Erosion Damage to Spells",
    valueRanges: [
      {
        min: 67,
        max: 69,
      },
      {
        min: 82,
        max: 84,
      },
    ],
    rawAffix: "Adds `(67-69)`- `(82-84)`Erosion Damage to Spells",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds {0}- {1}Physical Damage to Spells",
    valueRanges: [
      {
        min: 67,
        max: 69,
      },
      {
        min: 82,
        max: 84,
      },
    ],
    rawAffix: "Adds `(67-69)`- `(82-84)`Physical Damage to Spells",
  },
  {
    equipmentTypeKey: "wand",
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds {0}- {1}Lightning Damage to Spells",
    valueRanges: [
      {
        min: 7,
        max: 9,
      },
      {
        min: 142,
        max: 144,
      },
    ],
    rawAffix: "Adds `(7-9)`- `(142-144)`Lightning Damage to Spells",
  },
] as const satisfies readonly BaseGearAffix[];

export type WandPrefixAffix = (typeof WAND_PREFIX_AFFIXES)[number];
